### PR TITLE
Upgrade to http-parser 2.7.1

### PR DESCRIPTION
**Pull request by wch**

### CODE REVIEW

**Comment by QuLogic** [comment]
Same question as #91? (I'm wondering if httpuv could be built against a system copy now).

**Comment by wch** [comment]
Our copy of http-parser has been modified from the original sources, so building against a system copy of it would not work.

**Comment by QuLogic** [comment]
Thanks! Is there any chance these changes might go upstream?

**Comment by wch** [comment]
Nope. They're very customized for the specific needs of httpuv.

**Pull request merged**
