### PR TITLE
Fix createPipeServer

### PR DESCRIPTION
**Pull request by PromyLOPh**
Listening fails with `invalid argument`, if we pass true here. This fixes issue #282 for me.

### CODE REVIEW

**Comment by wch** [comment]
Looks good - can you add an entry to NEWS.md, and bump the version in DESCRIPTION and NEWS to 1.5.4.9001?

**Comment by PromyLOPh** [comment]
All done. It would probably we wise to add a testcase as well, because I don’t see one for `startPipeServer` yet. I’m not a R guru though and thus don’t know how to do that properly.

**Comment by wrodriguezz** [comment]
Hello folks, I wonder if the proposed PR will be merged or the potential fix be included on the next bump.

**Review by wch — APPROVED** [review]

**Comment by wch** [comment]
@wrodriguezz Thanks for the reminder. I just merged the PR.

**Comment by wrodriguezz** [comment]
Thank you, @wch!

**Pull request merged**
